plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
}

android {
    compileSdk 35
    namespace 'com.example.psychologicaltestapp'
    defaultConfig {
        applicationId "com.example.psychologicaltestapp"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        vectorDrawables {
            useSupportLibrary = true
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "androidx.recyclerview:recyclerview:1.4.0"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Coroutines Core
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0'

    // Coroutines Android
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'

    //Interstitial ads
    implementation 'com.google.android.gms:play-services-ads:24.4.0' // o la más reciente

    // For control over item selection of both touch and mouse driven selection
    implementation "androidx.recyclerview:recyclerview-selection:1.2.0"
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.google.code.gson:gson:2.10.1' // Gson dependency

    // Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:33.16.0') // Use the latest BoM version
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation("com.google.firebase:firebase-analytics")
    implementation "com.google.firebase:firebase-firestore-ktx:25.1.4"
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation "com.google.firebase:firebase-functions-ktx"

    // Glide library
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    //AI
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'


    implementation 'com.squareup.okhttp3:okhttp:4.9.3'

    // Import the BoM for the Firebase platform
    implementation(platform("com.google.firebase:firebase-bom:33.16.0")) // Use the latest BoM version

    // Add the dependency for the Firebase Authentication library
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation("com.google.firebase:firebase-auth")

    // If you're using Kotlin, you might also want the KTX (Kotlin extensions) library
    implementation("com.google.firebase:firebase-auth-ktx")
    implementation 'com.google.firebase:firebase-database-ktx:21.0.0'
    // TESTING (lo que necesitas restaurar)
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    //Billing
    implementation 'com.android.billingclient:billing-ktx:6.2.1'

    kapt 'com.github.bumptech.glide:compiler:4.16.0'
}